### ISSUE TITLE
Ошибки.

### ISSUE THREAD

**Issue by shelllshock** [petrpopov/VertMinerBot#1]
<img width="1141" alt="Снимок экрана 2024-07-10 в 21 02 35" src="https://github.com/petrpopov/VertMinerBot/assets/172393950/af930cfe-cfb0-4efa-9bf7-7d535c89438d">

Добрый день, сегодня установил, но уже не работает. Если есть возможность починить - буду признателен!

**Comment by petrpopov** [comment]
Добрый день. Только что проверил у себя локально и на сервере, работает.
На всякий случай сделал загрузку метода /missions необязательным (включается в конфиге bot/config/config.py или в .env параметром LOAD_MISSIONS - по умолчанияю сейчас стоит False), его результат все равно дальше по коду не используется, сделано было только для эмуляции аналогичного поведения на реальном устройстве.

Такое впечатление, что у вас отработала успешно загрузка профиля (метод /account) и сломалось дальше на /missions
Попробуйте запустить заново с обновленным кодом, можно на всякий случай пересобрать принудительно контейнер:

`docker compose up --build`
